
services:
  - type: web
    name: octopus-ai-docker
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "uvicorn server_main:app --host 0.0.0.0 --port 10000"
